package protocol

import ("encoding/json"; "flag"; "io"; "os"; "path/filepath"; "time")
type sessionDirResolver interface{GetSessionDir(string)(string,error)}; type sessionFileResolver interface{ResolveSessionFile(string,string)string}; type sessionIDProvider interface{GetSessionID(*HookInputJSON)string}; type sessionReader interface{ReadSession(*HookInputJSON)(AgentSessionJSON,error)}; type sessionWriter interface{WriteSession(AgentSessionJSON)error}; type transcriptReader interface{ReadTranscript(string)([]byte,error)}; type chunker interface{ChunkTranscript([]byte,int)([][]byte,error);ReassembleTranscript([][]byte)([]byte,error)}; type preparer interface{PrepareTranscript(string)error}; type formatter interface{FormatResumeCommand(string)string}; type hooks interface{ParseHook(string,[]byte)(*EventJSON,error);InstallHooks(bool,bool)(int,error);UninstallHooks()error;AreHooksInstalled()bool}; type analyzer interface{GetTranscriptPosition(string)(int,error);ExtractModifiedFiles(string,int)([]string,int,error);ExtractPrompts(string,int)([]string,error);ExtractSummary(string)(string,bool,error)}; type calculator interface{CalculateTokens([]byte,int)(TokenUsageResponse,error)}
func WriteJSON(w io.Writer,v any)error{e:=json.NewEncoder(w);e.SetEscapeHTML(false);return e.Encode(v)}
func ReadJSON[T any](r io.Reader)(*T,error){var v T;err:=json.NewDecoder(r).Decode(&v);return &v,err}
func RepoRoot()string{if s:=os.Getenv("ENTIRE_REPO_ROOT");s!=""{return s};s,_:=os.Getwd();return s}
func HandleGetSessionID(in io.Reader,out io.Writer,p sessionIDProvider)error{v,e:=ReadJSON[HookInputJSON](in);if e!=nil{return e};return WriteJSON(out,SessionIDResponse{p.GetSessionID(v)})}
func HandleGetSessionDir(a []string,out io.Writer,p sessionDirResolver)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);r:=f.String("repo-path","","");if e:=f.Parse(a);e!=nil{return e};s,e:=p.GetSessionDir(*r);return WriteJSON(out,SessionDirResponse{s})}
func HandleResolveSessionFile(a []string,out io.Writer,p sessionFileResolver)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);d:=f.String("session-dir","","");id:=f.String("session-id","","");if e:=f.Parse(a);e!=nil{return e};return WriteJSON(out,SessionFileResponse{p.ResolveSessionFile(*d,*id)})}
func HandleReadSession(in io.Reader,out io.Writer,p sessionReader)error{v,e:=ReadJSON[HookInputJSON](in);if e!=nil{return e};s,e:=p.ReadSession(v);if e!=nil{return e};return WriteJSON(out,s)}
func HandleWriteSession(in io.Reader,p sessionWriter)error{v,e:=ReadJSON[AgentSessionJSON](in);if e!=nil{return e};return p.WriteSession(*v)}
func HandleReadTranscript(a []string,out io.Writer,p transcriptReader)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("session-ref","","");if e:=f.Parse(a);e!=nil{return e};b,e:=p.ReadTranscript(*s);if e!=nil{return e};_,e=out.Write(b);return e}
func HandleChunkTranscript(a []string,in io.Reader,out io.Writer,p chunker)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);n:=f.Int("max-size",0,"");if e:=f.Parse(a);e!=nil{return e};b,e:=io.ReadAll(in);if e!=nil{return e};c,e:=p.ChunkTranscript(b,*n);if e!=nil{return e};return WriteJSON(out,ChunkResponse{c})}
func HandleReassembleTranscript(in io.Reader,out io.Writer,p chunker)error{v,e:=ReadJSON[ChunkResponse](in);if e!=nil{return e};b,e:=p.ReassembleTranscript(v.Chunks);if e!=nil{return e};_,e=out.Write(b);return e}
func HandlePrepareTranscript(a []string,p preparer)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("session-ref","","");if e:=f.Parse(a);e!=nil{return e};return p.PrepareTranscript(*s)}
func HandleFormatResumeCommand(a []string,out io.Writer,p formatter)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("session-id","","");if e:=f.Parse(a);e!=nil{return e};return WriteJSON(out,ResumeCommandResponse{p.FormatResumeCommand(*s)})}
func HandleParseHook(a []string,in io.Reader,out io.Writer,p hooks)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);h:=f.String("hook","","");if e:=f.Parse(a);e!=nil{return e};b,e:=io.ReadAll(in);if e!=nil{return e};v,e:=p.ParseHook(*h,b);if e!=nil{return e};if v==nil{_,e=out.Write([]byte("null\n"));return e};return WriteJSON(out,v)}
func HandleInstallHooks(a []string,out io.Writer,p hooks)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);l:=f.Bool("local-dev",false,"");force:=f.Bool("force",false,"");if e:=f.Parse(a);e!=nil{return e};n,e:=p.InstallHooks(*l,*force);if e!=nil{return e};return WriteJSON(out,HooksInstalledCountResponse{n})}
func HandleGetTranscriptPosition(a []string,out io.Writer,p analyzer)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("path","","");if e:=f.Parse(a);e!=nil{return e};n,e:=p.GetTranscriptPosition(*s);return WriteJSON(out,TranscriptPositionResponse{n})}
func HandleExtractModifiedFiles(a []string,out io.Writer,p analyzer)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("path","","");o:=f.Int("offset",0,"");if e:=f.Parse(a);e!=nil{return e};x,n,e:=p.ExtractModifiedFiles(*s,*o);return WriteJSON(out,ExtractFilesResponse{x,n})}
func HandleExtractPrompts(a []string,out io.Writer,p analyzer)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("session-ref","","");o:=f.Int("offset",0,"");if e:=f.Parse(a);e!=nil{return e};x,e:=p.ExtractPrompts(*s,*o);return WriteJSON(out,ExtractPromptsResponse{x})}
func HandleExtractSummary(a []string,out io.Writer,p analyzer)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);s:=f.String("session-ref","","");if e:=f.Parse(a);e!=nil{return e};x,h,e:=p.ExtractSummary(*s);return WriteJSON(out,ExtractSummaryResponse{x,h})}
func HandleCalculateTokens(a []string,in io.Reader,out io.Writer,p calculator)error{f:=flag.NewFlagSet("",flag.ContinueOnError);f.SetOutput(io.Discard);o:=f.Int("offset",0,"");if e:=f.Parse(a);e!=nil{return e};b,e:=io.ReadAll(in);if e!=nil{return e};x,e:=p.CalculateTokens(b,*o);if e!=nil{return e};return WriteJSON(out,x)}
var _ = filepath.Join; var _ = time.Now
